import type { LevelCurve } from "./demand.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** supabase/curves.seed.sql text. Re-runnable (upsert). Rows reference garage_levels, so run supabase/seed.sql first. */
export function renderCurvesSql(curves: LevelCurve[]): string {
  const rows = curves.map((c) => `  (${q(c.garageId)}, ${c.levelIndex}, ${c.dow}, '{${c.pct.join(",")}}')`);
  return `-- GENERATED by scripts/gen-curves.ts (npm run curves) from data/raw/timetable.json. Do not edit by hand.
-- SIMULATED targets shaped by VT's class timetable (seat capacity, not enrollment) - not sensor data.
insert into public.garage_level_curves (garage_id, level_index, dow, pct)
values
${rows.join(",\n")}
on conflict (garage_id, level_index, dow) do update set pct = excluded.pct;
`;
}
