import type { GarageLevel } from "../types.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** supabase/seed.sql text for the bundled sample counts. Re-runnable: it resets counts to the seed. */
export function renderSeedSql(levels: Record<string, GarageLevel[]>): string {
  const rows = Object.entries(levels).flatMap(([garageId, ls]) =>
    ls.map((l, i) => `  (${q(garageId)}, ${i}, ${q(l.label)}, ${l.capacity}, ${l.occupied}, ${l.adaCapacity}, ${l.adaOccupied})`),
  );
  return `-- GENERATED by scripts/gen-seed.ts from src/data/garages.ts. Do not edit by hand.
-- Re-running this file resets every level to the bundled sample counts.
insert into public.garage_levels (garage_id, level_index, label, capacity, occupied, ada_capacity, ada_occupied)
values
${rows.join(",\n")}
on conflict (garage_id, level_index) do update set
  label = excluded.label,
  capacity = excluded.capacity,
  occupied = excluded.occupied,
  ada_capacity = excluded.ada_capacity,
  ada_occupied = excluded.ada_occupied;
`;
}
