"""Parity check: the Python port must reproduce supabase/curves.seed.sql (generated by the TypeScript build) exactly.
Run from the repo root: python3 databricks/tests/test_parity.py  (or: npm run test:py)"""
import json
import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "databricks" / "src"))
import hokiepark_demand as hd  # noqa: E402

load = lambda p: json.loads((ROOT / p).read_text())  # noqa: E731


class Parity(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.timetable = load("data/raw/timetable.json")
        cls.codes = load("data/timetable-building-codes.json")
        cls.points = load("databricks/data/building_points.json")
        cls.garages = load("databricks/data/garages.json")
        cls.placed = hd.place(cls.timetable["meetings"], cls.codes, cls.points)
        cls.curves = hd.build_level_curves(cls.placed, cls.garages)

    def test_rows_match_the_typescript_generated_sql_exactly(self):
        sql = (ROOT / "supabase" / "curves.seed.sql").read_text()
        self.assertIn(hd.render_rows(self.curves), sql, "Python curves differ from supabase/curves.seed.sql (re-run npm run curves / databricks:inputs, or fix the port)")

    def test_full_sql_differs_only_in_header_comment(self):
        ts = (ROOT / "supabase" / "curves.seed.sql").read_text().split("\n", 1)[1]
        py = hd.render_seed_sql(self.curves).split("\n", 1)[1]
        self.assertEqual(ts, py)

    def test_coverage_matches_documented_99_percent(self):
        placed, total = hd.coverage(self.timetable["meetings"], self.codes, self.points)
        self.assertEqual((placed, total), (421235, 424917))

    def test_shape(self):
        self.assertEqual(len(self.curves), sum(len(g["levels"]) for g in self.garages) * 5)
        for c in self.curves:
            self.assertEqual(len(c["pct"]), 96)
            self.assertTrue(all(isinstance(v, int) and 0 <= v <= 100 for v in c["pct"]))

    def test_notebook_sort_order_gives_identical_curves(self):
        # The notebooks rebuild `placed` from a Spark table and sort it; that order must not change the result.
        shuffled = sorted(reversed(self.placed), key=lambda p: (p["group"]["building"], p["group"]["startMin"], "".join(p["group"]["days"])))
        self.assertEqual(hd.build_level_curves(shuffled, self.garages), self.curves)

    def test_js_round_is_half_up(self):
        self.assertEqual([hd.js_round(x) for x in (0.5, 1.5, 2.5, 2.4999)], [1, 2, 3, 2])

    def test_no_classes_means_staff_only_and_far_class_is_ignored(self):
        g = self.garages
        none = hd.build_level_curves([], g)
        far = hd.build_level_curves([{"group": {"days": ["M"], "startMin": 600, "endMin": 650, "capacity": 200, "building": "X"}, "lat": 37.5, "lon": -80.4}], g)
        self.assertEqual(none, far)

    def test_sensitivity_helpers(self):
        self.assertEqual(hd.mean_abs_diff(self.curves, self.curves), 0.0)
        wider = dict(hd.MODEL, radius_m=1200)
        self.assertGreater(hd.mean_abs_diff(hd.build_level_curves(self.placed, self.garages, wider), self.curves), 0.0)
        self.assertGreater(hd.level_hours_at_or_above(self.curves, "perry-street", 0), 0.0)

    def test_summarize_reports_a_busy_wednesday(self):
        s = {r["garage_id"]: r for r in hd.summarize(self.curves, self.garages)}
        self.assertGreaterEqual(s["perry-street"]["peak_fill_pct"], 90)
        self.assertLessEqual(s["perry-street"]["max_15min_change"], 15)


if __name__ == "__main__":
    unittest.main(verbosity=2)
