/**
 * Bundles supabase/functions/advisor/{main,handler}.ts + the shared spec into ONE file, supabase/functions/advisor/index.ts,
 * that can be pasted into the Supabase dashboard editor (no CLI or Deno needed here). Run: npm run advisor:build
 * (tests fail if the committed index.ts is stale). Also exports `bundle()` for that test.
 */
import { build } from "esbuild";
import { writeFileSync } from "node:fs";

const root = new URL("../", import.meta.url).pathname;
export const OUT = `${root}supabase/functions/advisor/index.ts`;

export async function bundle(): Promise<string> {
  const r = await build({
    entryPoints: [`${root}supabase/functions/advisor/main.ts`],
    bundle: true,
    write: false,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    legalComments: "none",
    banner: { js: "// GENERATED by scripts/build-advisor.ts (npm run advisor:build). Do not edit by hand: change handler.ts / advisor-spec.ts and rebuild.\n// Paste this whole file into Supabase -> Edge Functions -> advisor. Secrets needed: GEMINI_API_KEY (and optionally GEMINI_MODEL, ALLOWED_ORIGINS)." },
  });
  return r.outputFiles[0]!.text;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(OUT, await bundle());
  console.log(`wrote ${OUT.replace(root, "")}`);
}
