-- HokiePark: class-schedule-shaped occupancy targets for the demo simulator.
-- Run AFTER 20260919000000_garage_levels.sql, then run supabase/curves.seed.sql (generated by `npm run curves`).
--
-- HONESTY NOTE: these targets are SIMULATED. They come from VT's public Timetable of Classes (seat CAPACITY, not enrollment)
-- blended with an assumed staff-workday shape. They are not sensor data and were not validated against any ground truth.

-- One row per (garage, level, weekday): the target percent-full for each of the day's 96 fifteen-minute buckets.
create table if not exists public.garage_level_curves (
  garage_id   text     not null,
  level_index smallint not null,
  dow         smallint not null check (dow between 1 and 5),        -- ISO weekday: 1 = Monday .. 5 = Friday
  pct         smallint[] not null,
  primary key (garage_id, level_index, dow),
  foreign key (garage_id, level_index) references public.garage_levels (garage_id, level_index) on delete cascade,
  constraint pct_has_96_buckets check (cardinality(pct) = 96),
  constraint pct_in_range       check (0 <= all (pct) and 100 >= all (pct))
);
comment on table public.garage_level_curves is 'Simulated target occupancy (percent) per 15-minute bucket, derived from the class timetable. Not sensor data.';

-- Private: the browser never needs these, so no policy and no grants for API roles.
alter table public.garage_level_curves enable row level security;
revoke all on public.garage_level_curves from anon, authenticated;

-- Single-row demo controls.
create table if not exists public.sim_config (
  id                 boolean  primary key default true check (id),   -- forces exactly one row
  tz                 text     not null default 'America/New_York',
  weekend_replay_dow smallint not null default 3 check (weekend_replay_dow between 1 and 5), -- Sat/Sun replay this weekday (3 = Wed, the busiest)
  dow_override       smallint check (dow_override between 1 and 5),  -- pin the weekday (1 = Mon .. 5 = Fri)
  clock_override     time                                           -- pin the time of day, e.g. '08:50' (null = real clock)
);
insert into public.sim_config (id) values (true) on conflict (id) do nothing;
alter table public.sim_config enable row level security;
revoke all on public.sim_config from anon, authenticated;

-- Replaces the random walk. Same name, so an existing pg_cron job keeps working.
-- Each call moves every level a bounded step toward its curve target for "now" (plus +/-1 jitter), so counts drift like
-- arrivals and departures instead of jumping. Levels with no curve rows fall back to the original random walk.
create or replace function public.simulate_occupancy_tick() returns void
language plpgsql as $$
declare
  cfg      public.sim_config%rowtype;
  v_local  timestamp;
  v_time   time;
  v_dow    int;
  v_bucket int;
begin
  select * into cfg from public.sim_config limit 1;
  v_local  := now() at time zone coalesce(cfg.tz, 'America/New_York');
  v_time   := coalesce(cfg.clock_override, v_local::time);
  v_dow    := coalesce(cfg.dow_override, extract(isodow from v_local)::int);
  if v_dow > 5 then v_dow := coalesce(cfg.weekend_replay_dow, 3); end if;
  v_bucket := least(95, (extract(hour from v_time)::int * 60 + extract(minute from v_time)::int) / 15);

  -- 1) levels that have a curve: step toward the target, never below the ADA spaces taken, never above capacity
  update public.garage_levels l
     set occupied = greatest(l.ada_occupied, least(l.capacity,
           l.occupied
           + greatest(-greatest(3, ceil(l.capacity * 0.08)::int),
                      least( greatest(3, ceil(l.capacity * 0.08)::int),
                             round(l.capacity * c.pct[v_bucket + 1] / 100.0)::int - l.occupied))
           + (floor(random() * 3)::int - 1)))
    from public.garage_level_curves c
   where c.garage_id = l.garage_id and c.level_index = l.level_index and c.dow = v_dow;

  update public.garage_levels l
     set ada_occupied = greatest(0, least(l.ada_capacity, l.occupied,
           l.ada_occupied
           + greatest(-1, least(1, round(l.ada_capacity * c.pct[v_bucket + 1] / 100.0)::int - l.ada_occupied))))
    from public.garage_level_curves c
   where c.garage_id = l.garage_id and c.level_index = l.level_index and c.dow = v_dow;

  -- 2) levels without a curve: the original bounded random walk
  update public.garage_levels l
     set occupied = greatest(l.ada_occupied, least(l.capacity, l.occupied + (floor(random() * 7)::int - 3)))
   where not exists (select 1 from public.garage_level_curves c where c.garage_id = l.garage_id and c.level_index = l.level_index and c.dow = v_dow);
  update public.garage_levels l
     set ada_occupied = greatest(0, least(l.ada_capacity, l.occupied, l.ada_occupied + (floor(random() * 3)::int - 1)))
   where not exists (select 1 from public.garage_level_curves c where c.garage_id = l.garage_id and c.level_index = l.level_index and c.dow = v_dow);
end;
$$;

revoke all on function public.simulate_occupancy_tick() from public, anon, authenticated;
